// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2HckMYdpq0vgBU4Ter4gc75Sdgacad0',
    appId: '1:369228791667:web:7b262848fce1f51c220f06',
    messagingSenderId: '369228791667',
    projectId: 'sipaagenda',
    authDomain: 'sipaagenda.firebaseapp.com',
    storageBucket: 'sipaagenda.firebasestorage.app',
    measurementId: 'G-2VVHZG567Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw1IUVN-l99HjTXdNVc356jy0WKXWbrFs',
    appId: '1:369228791667:android:0a559089eae1574d220f06',
    messagingSenderId: '369228791667',
    projectId: 'sipaagenda',
    storageBucket: 'sipaagenda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtG1TAZsQDIMrU3XPMpLfuKKa6px-AoGs',
    appId: '1:369228791667:ios:c34dd9dfd86427f2220f06',
    messagingSenderId: '369228791667',
    projectId: 'sipaagenda',
    storageBucket: 'sipaagenda.firebasestorage.app',
    iosBundleId: 'com.example.sipaAgend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtG1TAZsQDIMrU3XPMpLfuKKa6px-AoGs',
    appId: '1:369228791667:ios:c34dd9dfd86427f2220f06',
    messagingSenderId: '369228791667',
    projectId: 'sipaagenda',
    storageBucket: 'sipaagenda.firebasestorage.app',
    iosBundleId: 'com.example.sipaAgend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg2HckMYdpq0vgBU4Ter4gc75Sdgacad0',
    appId: '1:369228791667:web:e1b92b0a713e08ee220f06',
    messagingSenderId: '369228791667',
    projectId: 'sipaagenda',
    authDomain: 'sipaagenda.firebaseapp.com',
    storageBucket: 'sipaagenda.firebasestorage.app',
    measurementId: 'G-WXSTZ9F735',
  );
}
